yarnPath: ".yarn/releases/yarn-berry.js"

# Stop yarn from whining about bUt iT iSn'T dEcLaRed iN iTs dEpEnDeNcIeS
# like damn you're filling up my whole terminal
packageExtensions:
  "eslint-config-airbnb-typescript@*":
    dependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
  "preact-jsx-chai@*":
    dependencies:
      preact: "*"
