yarnPath: ".yarn/releases/yarn-berry.js"

# Stop yarn from whining about bUt iT iSn'T dEcLaRed iN iTs dEpEnDeNcIeS
# like damn you're filling up my whole terminal
packageExtensions:
  "@types/node@*":
    dependencies:
      events: "*"
      util: "*"
      url: "*"
      querystring: "*"
